language: python

# version python
python:
  - 3.7
# branches de developpement qui seront indexées par travis
branches:
  only:
  - main
  - develop

#service
services:
  - docker

# installation de prerequis
before_script:
  - pip install -r requirements.txt
  - pip install mysql-connector-python-rf
  - docker pull bitnami/kubectl
  - docker login -u $USER_DOCKER  -p $PWR_DOCKER
  # - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
  # - chmod +x kubectl && sudo mv kubectl /usr/local/bin/kubectl


script:
  - python -m unittest discover -v
  # - echo "$PWR_DOCKER" | docker login -u "$USER_DOCKER" --password-stdin
  # - docker build -t <dockerUser>/pypytest:$TRAVIS_BUILD_NUMBER .
  # - docker push <dockerUser>/pypytest
  
# creation d'image et sa savegarde dans le docker
after_success:
  - docker build -t etslog680/image_hvac:latest .
  # - docker push etslog680/image_hvac:latest
  - sed -i -e 's|KUBE_CA|'"${KUBE_CA}"'|g' manifests-k8s\kubeconfig
  - sed -i -e 's|KUBE_ENDPOINT|'"${KUBE_ENDPOINT}"'|g' manifests-k8s\kubeconfig
  - sed -i -e 's|KUBE_CLUSTER_NAME|'"${KUBE_CLUSTER_NAME}"'|g' manifests-k8s\manifests-k8s\kubeconfig
  - sed -i -e 's|KUBE_USER_NAMESPACE|'"${KUBE_USER_NAMESPACE}"'|g' manifests-k8s\manifests-k8s\kubeconfig
  - sed -i -e 's|KUBE_ADMIN_CERT|'"${KUBE_ADMIN_CERT}"'|g' manifests-k8s\manifests-k8s\kubeconfig
  - sed -i -e 's|KUBE_ADMIN_KEY|'"${KUBE_ADMIN_KEY}"'|g' manifests-k8s\kubeconfig
  - sed -i -e 's|KUBE_USERNAME|'"${KUBE_USERNAME}"'|g' manifests-k8s\kubeconfig
  - echo "${TRAVIS_BUILD_DIR}"
  # - docker run -v ${TRAVIS_BUILD_DIR}:/kube smesch/kubectl kubectl --kubeconfig /kube/kubeconfig set image deployment/${K8S_DEPLOYMENT_NAME} ${K8S_DEPLOYMENT_NAME}=${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:$TRAVIS_BUILD_ID
  # - kubectl apply -f .\hvac-deployment.yaml

#fin du code