language: python

# branches de developpement
branches:
  only:
  - main
  - develop

# version python
python:
  - 3.7

#service
services:
  - docker

# installation de prerequis
before_script:
  - pip install -r requirements.txt

script:
  - python -m unittest discover -v
after_success:
  - docker build -t hvac_controller .
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag hvac_controller $DOCKER_USER/hvac_controller:latest
  - docker push $DOCKER_USER/hvac_controller:latest
