language: python

# version python
python:
  - 3.7
# branches de developpement
branches:
  only:
  - main
  - develop

#service
services:
  - docker

# installation de prerequis
before_script:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest