language: python

# version python
python:
  - 3.7
# branches de developpement qui seront indexées par travis
branches:
  only:
  - main
  - develop

#service
services:
  - docker

# installation de prerequis
before_script:
  - pip install -r requirements.txt
  - pip install mysql-connector-python-rf
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
  - chmod +x kubectl && sudo mv kubectl /usr/local/bin/kubectl


script:
  - python -m unittest discover -v
  - cat $KUBECONFIG > kubeconfig
  - cat kubeconfig
  # - echo "$PWR_DOCKER" | docker login -u "$USER_DOCKER" --password-stdin
  # - docker build -t <dockerUser>/pypytest:$TRAVIS_BUILD_NUMBER .
  # - docker push <dockerUser>/pypytest
  
# creation d'image et sa savegarde dans le docker
after success:
  # - docker build -t etslog680/image_hvac:latest .
  # - docker login -u $USER_DOCKER  -p $PWR_DOCKER
  # - docker push etslog680/image_hvac:latest
  # - kubectl apply -f .\hvac-deployment.yaml

#fin du code