language: python

# version python
python:
  - 3.7
# branches de developpement qui seront indexées par travis
branches:
  only:
  - main
  - develop

#service
services:
  - docker

# installation de prerequis
before_script:
  - pip install -r requirements.txt

# command to run tests
script:
  - python -m unittest discover -v

# creation d'image et sa savegarde dans le docker
after success:
  - docker built -t image_hvac .
  - docker login -u $USER_DOCKER  -p $PWR_DOCKER
  - docker tag image_hvac etslog680/image_hvac:latest
  - docker push $USER_DOCKER/image_hvac:latest
